Red: pre_victory_road
Blue: pre_victory_road
Gold: no_mt_silver
Silver: no_mt_silver
Ruby: pre_victory_road
Sapphire: pre_victory_road
Solus RGB: pre_victory_road
Diamond: pre_victory_road
Pearl: pre_victory_road
